# Boston Housing

Nicolás Martínez Gutiérrez

751746

01/09/2025

In [89]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import statsmodels.api as sm

In [90]:
data = pd.read_excel("Boston Housing Dataset 1978.xlsx")

In [91]:
data.head(5)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [92]:
data.tail(5)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

In [93]:
data.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,452.000000
mean,1.269195,13.295257,9.205158,0.140765,1.101175,15.679800,58.744660,6.173308,78.063241,339.317787,42.614980,332.791107,11.537806,23.750442
std,2.399207,23.048697,7.169630,0.312765,1.646991,27.220206,33.104049,6.476435,203.542157,180.670077,87.585243,125.322456,6.064932,8.808602
min,0.000000,0.000000,0.000000,0.000000,0.385000,3.561000,1.137000,1.129600,1.000000,20.200000,2.600000,0.320000,1.730000,6.300000
25%,0.049443,0.000000,3.440000,0.000000,0.449000,5.961500,32.000000,2.430575,4.000000,254.000000,17.000000,364.995000,6.877500,18.500000
50%,0.144655,0.000000,6.960000,0.000000,0.538000,6.322500,65.250000,3.925850,5.000000,307.000000,18.900000,390.660000,10.380000,21.950000
75%,0.819623,18.100000,18.100000,0.000000,0.647000,6.949000,89.975000,6.332075,24.000000,403.000000,20.200000,395.615000,15.015000,26.600000
max,9.966540,100.000000,27.740000,1.000000,7.313000,100.000000,100.000000,24.000000,666.000000,711.000000,396.900000,396.900000,34.410000,50.000000

In [94]:
data2 = data.dropna()
data2

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

In [95]:
data2.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000
mean,1.420825,12.721239,10.304889,0.077434,0.540816,6.343538,65.557965,4.043570,7.823009,377.442478,18.247124,369.826504,11.441881,23.750442
std,2.495894,24.326032,6.797103,0.267574,0.113816,0.666808,28.127025,2.090492,7.543494,151.327573,2.200064,68.554439,6.156437,8.808602
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,6.300000
25%,0.069875,0.000000,4.930000,0.000000,0.447000,5.926750,40.950000,2.354750,4.000000,276.750000,16.800000,377.717500,6.587500,18.500000
50%,0.191030,0.000000,8.140000,0.000000,0.519000,6.229000,71.800000,3.550400,5.000000,307.000000,18.600000,392.080000,10.250000,21.950000
75%,1.211460,20.000000,18.100000,0.000000,0.605000,6.635000,91.625000,5.401100,7.000000,411.000000,20.200000,396.157500,15.105000,26.600000
max,9.966540,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,34.410000,50.000000

### Regresión Lineal Múltiple

In [96]:
y = data2["MEDV"]
x = data2.drop(columns=["MEDV"])

In [97]:
n = len(y)
n

452

In [98]:
unos = np.ones([n,1])

In [99]:
X = np.column_stack([unos, x])

In [100]:
ols = sm.OLS(y, X)

In [101]:
results = ols.fit()

In [102]:
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                   MEDV   R-squared:                       0.741
Model:                            OLS   Adj. R-squared:                  0.733
Method:                 Least Squares   F-statistic:                     96.16
Date:                Mon, 01 Sep 2025   Prob (F-statistic):          2.64e-119
Time:                        17:43:41   Log-Likelihood:                -1319.4
No. Observations:                 452   AIC:                             2667.
Df Residuals:                     438   BIC:                             2724.
Df Model:                          13
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         20.8664      5.477      3.810      0.000      10.102      31.631
x1            -0.2380      0.224     -1.063      0.288      -0.678       0.202
x2             0.0382      0.013      2.858      0.004       0.012       0.065
x3             0.0514      0.060      0.861      0.390      -0.066       0.169
x4             2.4350      0.830      2.935      0.004       0.804       4.066
x5           -11.6580      3.928     -2.968      0.003     -19.378      -3.938
x6             5.1102      0.455     11.235      0.000       4.216       6.004
x7            -0.0061      0.013     -0.465      0.642      -0.032       0.020
x8            -1.2715      0.196     -6.495      0.000      -1.656      -0.887
x9             0.2944      0.085      3.448      0.001       0.127       0.462
x10           -0.0114      0.004     -3.145      0.002      -0.018      -0.004
x11           -0.8310      0.127     -6.544      0.000      -1.081      -0.581
x12            0.0123      0.004      3.505      0.001       0.005       0.019
x13           -0.5208      0.057     -9.068      0.000      -0.634      -0.408
==============================================================================
Omnibus:                      203.769   Durbin-Watson:                   1.181
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1595.387
Skew:                           1.762   Prob(JB):                         0.00
Kurtosis:                      11.502   Cond. No.                     1.55e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.55e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [103]:
data3 = data2.drop_duplicates()
data3

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

In [104]:
data3.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000
mean,1.420825,12.721239,10.304889,0.077434,0.540816,6.343538,65.557965,4.043570,7.823009,377.442478,18.247124,369.826504,11.441881,23.750442
std,2.495894,24.326032,6.797103,0.267574,0.113816,0.666808,28.127025,2.090492,7.543494,151.327573,2.200064,68.554439,6.156437,8.808602
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,6.300000
25%,0.069875,0.000000,4.930000,0.000000,0.447000,5.926750,40.950000,2.354750,4.000000,276.750000,16.800000,377.717500,6.587500,18.500000
50%,0.191030,0.000000,8.140000,0.000000,0.519000,6.229000,71.800000,3.550400,5.000000,307.000000,18.600000,392.080000,10.250000,21.950000
75%,1.211460,20.000000,18.100000,0.000000,0.605000,6.635000,91.625000,5.401100,7.000000,411.000000,20.200000,396.157500,15.105000,26.600000
max,9.966540,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,34.410000,50.000000

### Escalamiento de Factores

In [105]:
CRIM_est= (data3["CRIM"] - data3["CRIM"].min()) / (data3["CRIM"].max() - data3["CRIM"].min())

In [106]:
CRIM_est.min(), CRIM_est.max()

(0.0, 1.0)

In [107]:
ZN_est   = (data3["ZN"]   - data3["ZN"].min())   / (data3["ZN"].max()   - data3["ZN"].min())

In [108]:
ZN_est.min(), ZN_est.max()

(0.0, 1.0)

In [109]:
INDUS_est= (data3["INDUS"]- data3["INDUS"].min())/ (data3["INDUS"].max()- data3["INDUS"].min())

In [110]:
INDUS_est.min(), INDUS_est.max()

(0.0, 1.0)

In [111]:
CHAS_est = (data3["CHAS"] - data3["CHAS"].min()) / (data3["CHAS"].max() - data3["CHAS"].min())

In [112]:
CHAS_est.min(), CHAS_est.max()

(0.0, 1.0)

In [113]:
NOX_est  = (data3["NOX"]  - data3["NOX"].min())  / (data3["NOX"].max()  - data3["NOX"].min())

In [114]:
NOX_est.min(), NOX_est.max()

(0.0, 1.0)

In [115]:
RM_est   = (data3["RM"]   - data3["RM"].min())   / (data3["RM"].max()   - data3["RM"].min())

In [116]:
RM_est.min(), RM_est.max()

(0.0, 1.0)

In [117]:
AGE_est  = (data3["AGE"]  - data3["AGE"].min())  / (data3["AGE"].max()  - data3["AGE"].min())

In [118]:
AGE_est.min(), AGE_est.max()

(0.0, 1.0)

In [119]:
DIS_est  = (data3["DIS"]  - data3["DIS"].min())  / (data3["DIS"].max()  - data3["DIS"].min())

In [120]:
DIS_est.min(), DIS_est.max()

(0.0, 1.0)

In [121]:
RAD_est  = (data3["RAD"]  - data3["RAD"].min())  / (data3["RAD"].max()  - data3["RAD"].min())

In [122]:
RAD_est.min(), RAD_est.max()

(0.0, 1.0)

In [123]:
TAX_est  = (data3["TAX"]  - data3["TAX"].min())  / (data3["TAX"].max()  - data3["TAX"].min())

In [124]:
TAX_est.min(), TAX_est.max()

(0.0, 1.0)

In [125]:
PTRATIO_est = (data3["PTRATIO"] - data3["PTRATIO"].min()) / (data3["PTRATIO"].max() - data3["PTRATIO"].min())

In [126]:
PTRATIO_est.min(), PTRATIO_est.max()

(0.0, 1.0)

In [127]:
B_est    = (data3["B"]    - data3["B"].min())    / (data3["B"].max()    - data3["B"].min())

In [128]:
B_est.min(), B_est.max()

(0.0, 1.0)

In [129]:
LSTAT_est= (data3["LSTAT"]- data3["LSTAT"].min())/ (data3["LSTAT"].max()- data3["LSTAT"].min())

In [130]:
LSTAT_est.min(), LSTAT_est.max()

(0.0, 1.0)

In [131]:
# for col in data3.columns:
#    if col == "MEDV": break
#    paso1 = data3[col] - data3[col].min()
#    paso2 = paso1/paso1.max()
#    data3[col] = paso2
# print(col)

### Regresión Lineal Múltiple después de Escalamiento

In [132]:
X_est = np.column_stack([CRIM_est, ZN_est, INDUS_est, CHAS_est, NOX_est, RM_est, AGE_est, DIS_est, RAD_est, TAX_est, PTRATIO_est, B_est, LSTAT_est])
y = data3["MEDV"]
n = len(y)
unos = np.ones((n, 1))
X_est = np.column_stack([unos, X_est])
ols = sm.OLS(y, X_est)
results = ols.fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                   MEDV   R-squared:                       0.741
Model:                            OLS   Adj. R-squared:                  0.733
Method:                 Least Squares   F-statistic:                     96.16
Date:                Mon, 01 Sep 2025   Prob (F-statistic):          2.64e-119
Time:                        17:43:41   Log-Likelihood:                -1319.4
No. Observations:                 452   AIC:                             2667.
Df Residuals:                     438   BIC:                             2724.
Df Model:                          13
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         19.9457      2.615      7.626      0.000      14.805      25.086
x1            -2.3708      2.230     -1.063      0.288      -6.753       2.011
x2             3.8221      1.337      2.858      0.004       1.194       6.450
x3             1.4010      1.627      0.861      0.390      -1.797       4.599
x4             2.4350      0.830      2.935      0.004       0.804       4.066
x5            -5.6658      1.909     -2.968      0.003      -9.418      -1.914
x6            26.6699      2.374     11.235      0.000      22.004      31.335
x7            -0.5917      1.272     -0.465      0.642      -3.092       1.908
x8           -13.9827      2.153     -6.495      0.000     -18.214      -9.752
x9             6.7722      1.964      3.448      0.001       2.912      10.632
x10           -5.9525      1.893     -3.145      0.002      -9.673      -2.232
x11           -7.8117      1.194     -6.544      0.000     -10.158      -5.465
x12            4.8836      1.393      3.505      0.001       2.145       7.622
x13          -17.0182      1.877     -9.068      0.000     -20.707     -13.330
==============================================================================
Omnibus:                      203.769   Durbin-Watson:                   1.181
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1595.387
Skew:                           1.762   Prob(JB):                         0.00
Kurtosis:                      11.502   Cond. No.                         32.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""